name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: swift build -c release --arch arm64 --arch x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: swift-bundler
          path: ./.build/apple/Products/Release/swift-bundler
